name: Node.js CI

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # Checkout the repository code

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify Node.js version

    - name: Install Dependencies
      run: npm install  # Command to install dependencies (no actual package.json needed)

    - name: Run Tests
      run: echo "No tests to run yet."  # Placeholder for running tests
